hosts:
    - address: localhost
      port: 22
      username: root
      password: 
      apply:
        - helloworld
#    - address:
#      port: 22
#      username: root
#      password:
#      apply:
#        - helloworld


triggers:
    restart_httpd:
        module_name: service
        action: restart
        service_name: lighttpd

menus:
    helloworld:
        - module_name: package
          action: install
          package_name: lighttpd
        - module_name: package
          action: install
          package_name: php-cgi
        - module_name: exec
          command:  lighty-enable-mod fastcgi fastcgi-php
        - module_name: file
          trigger: restart_httpd
          action: create
          content: |
            <?php
            header("Content-Type: text/plain");
            echo "Hello, world!\n";
            ?>
          path: /var/www/html/index.php
          owner: www-data
          group: www-data
          mode: 777

